### ISSUE TITLE
Error du: illegal option -- -

### ISSUE THREAD

**Issue by backspaces** [dylang/space-hogs#1]
Running on mac, with the du in /usr/bin, I get this error looking at my ~/.atom/packages dir.

space-hogs
Error: Command failed: du --max-depth=1
du: illegal option -- -
usage: du [-H | -L | -P] [-a | -s | -d depth] [-c] [-h | -k | -m | -g] [-x] [-I mask] [file ...]

```
at ChildProcess.exithandler (child_process.js:203:12)
at emitTwo (events.js:87:13)
at ChildProcess.emit (events.js:172:7)
at maybeClose (internal/child_process.js:818:16)
at Socket.<anonymous> (internal/child_process.js:319:11)
at emitOne (events.js:77:13)
at Socket.emit (events.js:169:7)
at Pipe._onclose (net.js:469:12)
```

**Comment by dylang** [comment]
Hi @backspaces, thanks for giving `space-hogs` a try!

Is it doing this for all paths?

I might have an upgraded version of `du` via `brew install coreutils` that adds `--max-depth`, so I may need to add support for both versions.

Can you paste the output to `du --help` here, or a similar command so I can see what flags your version of `du` has? Thanks!

**Comment by dylang** [comment]
Oops, I just re-read your bug report and it looks like there might be a directory called `-` which is messing up `du`. I'll see if I can avoid that issue. 

When I try it:

```
$ space-hogs ~/.atom/packages
86 MB ~/.atom/packages
Directories larger than 6 MB
├──  8 MB [▒   ] /merge-conflicts
├── 10 MB [▒   ] /travis-ci-status/node_modules
├──  6 MB [▒   ] /sourcegraph-atom/node_modules/atom-space-pen-views/node_modules/space-pen/node_modules
├──  8 MB [▒   ] /esformatter/node_modules/esformatter-jsx/node_modules
├──  7 MB [▒   ] /esformatter/node_modules/esformatter-wordpress/node_modules
├──  8 MB [▒   ] /esformatter/node_modules/esformatter/node_modules/babel-traverse/node_modules
└── 39 MB [▒▒  ] (everything else)
    86 MB Total
```

(I only have a few plugins installed, I'm mainly a Webstorm user.)

**Comment by backspaces** [comment]
Thanks for the nifty project!

The du man page for me is below. The error report usage seems to agree:
usage: du [-H | -L | -P] [-a | -s | -d depth] [-c] [-h | -k | -m | -g] [-x] [-I mask] [file ...]

And yes It does fail similarly for all paths. Ironically there is no "help" option for du. Ancient!

Env: Mac latest on a recent MBP.

DU(1)             BSD General Commands Manual            DU(1)

NAME
     du -- display disk usage statistics

SYNOPSIS
     du [-H | -L | -P] [-a | -s | -d depth] [-c] [-h | -k | -m | -g] [-x]
    [-I mask] [file ...]

DESCRIPTION
     The du utility displays the file system block usage for each file argu-
     ment and for each directory in the file hierarchy rooted in each direc-
     tory argument.  If no file is specified, the block usage of the hierarchy
     rooted in the current directory is displayed.

```
 The options are as follows:

 -a      Display an entry for each file in a file hierarchy.

 -c      Display a grand total.

 -d depth
     Display an entry for all files and directories depth directories
     deep.

 -H      Symbolic links on the command line are followed, symbolic links
     in file hierarchies are not followed.

 -h      "Human-readable" output.  Use unit suffixes: Byte, Kilobyte,
     Megabyte, Gigabyte, Terabyte and Petabyte.

 -I mask
     Ignore files and directories matching the specified mask.

 -g      Display block counts in 1073741824-byte (1-Gbyte) blocks.

 -k      Display block counts in 1024-byte (1-Kbyte) blocks.

 -L      Symbolic links on the command line and in file hierarchies are
     followed.

 -m      Display block counts in 1048576-byte (1-Mbyte) blocks.

 -P      No symbolic links are followed.  This is the default.

 -r      Generate messages about directories that cannot be read, files
     that cannot be opened, and so on.  This is the default case.
     This option exists solely for conformance with X/Open Portability
     Guide Issue 4 (``XPG4'').

 -s      Display an entry for each specified file.  (Equivalent to -d 0)

 -x      File system mount points are not traversed.

 The du utility counts the storage used by symbolic links and not the
 files they reference unless the -H or -L option is specified.  If either
 the -H or -L options are specified, storage used by any symbolic links
 which are followed is not counted or displayed.  If more than one of the
 -H, -L, and -P options is specified, the last one given is used.

 Files having multiple hard links are counted (and displayed) a single
 time per du execution.  Directories having multiple hard links (typically
 Time Machine backups) are counted a single time per du execution.
```

ENVIRONMENT
     BLOCKSIZE  If the environment variable BLOCKSIZE is set, and the -k
        option is not specified, the block counts will be displayed in
        units of that size block.  If BLOCKSIZE is not set, and the -k
        option is not specified, the block counts will be displayed in
        512-byte blocks.

LEGACY DESCRIPTION
     In legacy mode, only one of the -H, -L, or -P options may be specified.

```
 The command will detect and report a SYMLOOP error (loop involving sym-
 bolic links).  In legacy mode, this is not the case.

 For more information about legacy mode, see compat(5).
```

SEE ALSO
     df(1), fts(3), compat(5), symlink(7), quot(8)

HISTORY
     A du command appeared in Version 1 AT&T UNIX.

BSD              June 2, 2004                  BSD

**Comment by dylang** [comment]
Okay, I built this for a version of `du` that not everyone has. Looks like I need to fix it! 

Thank you for identifying this issue!

I'll have a new version in a few hours, I have travel and kid duty now. :smile:

**Comment by dylang** [comment]
I pushed a new version for support for `BSD du(1)`, can you tell me if it works for you?

```
$ space-hogs --version
1.4.0
```

**Comment by backspaces** [comment]
Works great! I really like the adaptive size threshold too.

**Comment by dylang** [comment]
> Works great!

Yay! Thanks for all your help!

> adaptive size threshold

Fancy description, I might have to steal that!

**Comment by whitetrefoil** [comment]
Oops... for the GNU du v8.4 (which is pre-installed on my ancient CentOS server) it support only --max-depth, it doesn't support -d...
